FROM apache/spark:3.5.0-python3

WORKDIR /app

COPY requirements.txt .
USER root
RUN pip install -r requirements.txt

COPY . .

CMD ["spark-submit", "--packages", "org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0", "consumer/consumer.py"]